services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=cinemark
      - MYSQL_ROOT_PASSWORD=02122001Luan
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  test-db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=cinemark_test
      - MYSQL_ROOT_PASSWORD=02122001Luan
    volumes:
      - mysql_data_test:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  prisma: 
    image: node:18
    depends_on:
      - db
      - test-db
    volumes:
      - ./prisma:/app/prisma
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npx prisma generate && npx prisma migrate deploy"

volumes:
  mysql_data:
  mysql_data_test: