services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=cinemark
      - MYSQL_ROOT_PASSWORD=02122001Luan
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  test-db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=cinemark_test
      - MYSQL_ROOT_PASSWORD=02122001Luan
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
